### ISSUE TITLE
Unable to ping hosts on local network

### ISSUE THREAD

**Issue by Muffinman** [adferrand/docker-backuppc#4]
Hi,

From within the docker container, it doesn't seem to be able to contact any local hosts on the network?
Looks like alpine doesn't include any `/etc/nsswitch.conf` file which may be forcing all DNS to be resolved remotely, however even after manually creating this file in the container it does not work.\

Any ideas?

From host:
```bash
$ ping matts-imac.local
PING matts-imac.local (192.168.10.31) 56(84) bytes of data.
64 bytes from Matts-iMac.local (192.168.10.31): icmp_seq=1 ttl=64 time=0.159 ms
64 bytes from Matts-iMac.local (192.168.10.31): icmp_seq=2 ttl=64 time=0.262 ms
^C
--- matts-imac.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.159/0.210/0.262/0.053 ms
```

From container:
```bash
/ # ping matts-imac.local
ping: unknown host matts-imac.local
```

My docker-compose.yml file:

```yml
version: "3.1"
services:
  backuppc:
    image: adferrand/backuppc
    container_name: backuppc
    ports:
      - "8080:8080"
    volumes:
      - /etc/backuppc:/etc/backuppc
      - /var/lib/backuppc:/home/backuppc
      - /media/backuppc:/data/backuppc
    environment:
      BACKUPPC_UUID: 114
      BACKUPPC_GUID: 122
      TZ: "Europe/London"
```
