### ISSUE TITLE
using volumes mounted via NFS

### ISSUE THREAD

**Issue by lwiechec** [adferrand/docker-backuppc#6]
Hello,

thank you for dockerizing BackupPC! 

This more of a question than - an issue. My docker host has a big share mounted via NFS using user 'wiechec' (UID: 1024) and group 'users' (GID: 100).

When I run BackupPC, I am getting this:

```
lukasz@NUSV199:~/work$ docker-compose -f docker-compose-backuppc.yml up
Starting backuppc ... 
Starting backuppc ... done
Attaching to backuppc
backuppc    | First run of the container. BackupPC will be installed.
backuppc    | If exist, configuration and data will be reused and upgraded as needed.
backuppc    | addgroup: gid '100' in use
backuppc exited with code 1
```

while my Docker compose script looks like this:

```yaml
backuppc:
  image: adferrand/backuppc:latest
  container_name: backuppc
  ports:
    - "8778:80"
  restart: always
  volumes:
    - /mnt/nas/lukasz/docker/volumes/backuppc/home_backuppc:/home/backuppc
    - /mnt/nas/lukasz/docker/volumes/backuppc/data_backuppc:/data/backuppc
    - /mnt/nas/lukasz/docker/volumes/backuppc/config:/etc/backuppc
  environment:
    - BACKUPPC_UUID=1024
    - BACKUPPC_GUID=100
    - BACKUPPC_WEB_USER=backuppc
    - BACKUPPC_WEB_PASSWD=backuppc
    - VIRTUAL_HOST=backuppc.docker-cdte.nu.majiic
    - VIRTUAL_PORT=8778
```

Any hint would be greatly appreciated!
